package view

import (
	"bufio"
	"fmt"
	"os"
	"strconv"
	"strings"

	"employee-management-app/model"
)

type DepartmentView struct {
	reader *bufio.Reader
}

// Constructor
func NewDepartmentView() *DepartmentView {

	return &DepartmentView{
		reader: bufio.NewReader(os.Stdin),
	}
}

// ==================================================
// DEPARTMENT MENU
// ==================================================

func (v *DepartmentView) ShowMenu() {

	fmt.Println()
	fmt.Println("========== DEPARTMENT MANAGEMENT ==========")
	fmt.Println("1. Add Department")
	fmt.Println("2. Find Department By ID")
	fmt.Println("3. Find All Departments")
	fmt.Println("4. Update Department")
	fmt.Println("5. Delete Department")
	fmt.Println("6. Back to Main Menu")
	fmt.Println("===========================================")
}

// ==================================================
// READ INTEGER
// ==================================================

func (v *DepartmentView) ReadInt(message string) int {

	for {

		fmt.Print(message)

		input, _ := v.reader.ReadString('\n')

		input = strings.TrimSpace(input)

		value, err := strconv.Atoi(input)

		if err == nil {
			return value
		}

		fmt.Println("Please enter a valid number.")
	}
}

// ==================================================
// READ STRING
// ==================================================

func (v *DepartmentView) ReadString(message string) string {

	fmt.Print(message)

	input, _ := v.reader.ReadString('\n')

	return strings.TrimSpace(input)
}

// ==================================================
// READ DEPARTMENT
// ==================================================

// Used when creating a department.
// ID is generated by PostgreSQL.

func (v *DepartmentView) ReadDepartment() model.Department {

	return model.Department{
		Name: v.ReadString("Enter Department Name: "),
	}
}

// ==================================================
// READ DEPARTMENT FOR UPDATE
// ==================================================

// ID is required when updating.

func (v *DepartmentView) ReadDepartmentForUpdate() model.Department {

	return model.Department{
		ID:   v.ReadInt("Enter Department ID: "),
		Name: v.ReadString("Enter Department Name: "),
	}
}

// ==================================================
// DISPLAY ONE DEPARTMENT
// ==================================================

func (v *DepartmentView) ShowDepartment(
	department model.Department,
) {

	fmt.Println("--------------------------------")
	fmt.Println("ID   :", department.ID)
	fmt.Println("Name :", department.Name)
	fmt.Println("--------------------------------")
}

// ==================================================
// DISPLAY ALL DEPARTMENTS
// ==================================================

func (v *DepartmentView) ShowDepartments(
	departments []model.Department,
) {

	if len(departments) == 0 {
		fmt.Println("No departments found.")
		return
	}

	for _, department := range departments {

		v.ShowDepartment(department)
	}
}

// ==================================================
// DISPLAY MESSAGE
// ==================================================

func (v *DepartmentView) ShowMessage(
	message string,
) {

	fmt.Println(message)
}
