CREATE TABLE IF NOT EXISTS products (id BIGSERIAL PRIMARY KEY, name VARCHAR(100) NOT NULL, price NUMERIC(12,2) NOT NULL CHECK(price > 0), stock INT NOT NULL CHECK(stock >= 0));
CREATE TABLE IF NOT EXISTS orders (id BIGSERIAL PRIMARY KEY, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS order_items (id BIGSERIAL PRIMARY KEY, order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE, product_id BIGINT NOT NULL REFERENCES products(id), quantity INT NOT NULL CHECK(quantity > 0), price NUMERIC(12,2) NOT NULL);
