CREATE TABLE IF NOT EXISTS employees (id BIGSERIAL PRIMARY KEY, name VARCHAR(100) NOT NULL);
CREATE TABLE IF NOT EXISTS attendance (id BIGSERIAL PRIMARY KEY, employee_id BIGINT NOT NULL REFERENCES employees(id), check_in TIMESTAMP NOT NULL, check_out TIMESTAMP);
CREATE TABLE IF NOT EXISTS leaves (id BIGSERIAL PRIMARY KEY, employee_id BIGINT NOT NULL REFERENCES employees(id), leave_date DATE NOT NULL, reason VARCHAR(250) NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'Pending');
